### ISSUE TITLE
image07 targetSG missing dependencies

### ISSUE THREAD

**Issue by pv33** [ivapylibs/detector#10]
Relies on roipoly that is not in canonical python packages. I have numpy, scipy, openCV, ROS.

It has been sourced from somewhere but not documented. Needs to be noted somewhere, either in the main README.md in a testing/README.md file or in the file proper.

**Comment by yiyeChen** [comment]
@pv33 

I have already noted that in the main README file under the [dependencies section](https://github.com/ivapylibs/detector#dependencies)
