### ISSUE TITLE
inImage: simple depth processing

### ISSUE THREAD

**Issue by pv33** [ivapylibs/detector#5]
Combine clipping with binarization (be careful with how you binarize given the clipped values!) on a depth image, such as from Mary's camera, to extract an object hovering in the air. The easiest is a hand, but anything works. The robot arm might work for example.

This is `image02_depthclip`` test script.

**Comment by yiyeChen** [comment]
I have pushed the depth data, where:

```testing/depth_raw_*.npz``` are raw data in float32 representing the meters of the shape ```(num_frames, H, W)```. Only contains 50 frames because of the file size limit. 

```testing/depth_proc_*.avi/png``` are preprocessed data in uint8 with each pixel value clipped and scaled.

```testing/depth_process.py``` contains the function for preprocessing.

**Comment by pv33** [comment]
@yiyeChen 
Yes, the best is to instantiate an ``improcessor``.  I've modified the code but am still on 16.04LTS so I can't test it out so easily. pip3 is broken. You'll have to fix any mistakes. Should be obvious.

I have committed and pushed.  
The last things to change is to make it so that the script is executabe and won't depend on where it is run to do the right thing.  Please look at the improcess test scripts (02 and 03) for how to extract the working directory of the python file, as well as the first line text to make executable.
