### ISSUE TITLE
inImage: depth video or image sequence processing

### ISSUE THREAD

**Issue by pv33** [ivapylibs/detector#6]
Upgrade the ``image02_depthclip`` test script from #5 to processing a video or an image sequence, whatever is easiest.  Have Yiye provide if needed, or generate fake data if he can't provide in a timely manner (delay should be no more than 1 hour to provision).  Since the video is short, it should fit here in the testing directory.

**Comment by yiyeChen** [comment]
Data provided. See #5

**Comment by Uio96** [comment]
I have finished the basic testing files. However, it still needs the camera pose info to get a better result. Yiye will provide me with the new data tomorrow and I will then update the code.
